---
title: "Project 1"
author: "Sofia Valdivieso-Sinyakov (sv23242)"
output: pdf_document
date: "2020-03-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

## Data Wrangling and Data Exploration

### Find data/Introduction:

  The original dataset I chose has 3,191 observations and 534 Variables stemming from many different national data servers. I selected for 6 particular variables. Each observation is labeled by a unique digit code, which I used later as the primary key to join the two self-made portions of the dataset back into one. The digit code was created for the dataset to label each unique observation. Each observation contains the population of a particular city (not selected for/identified here but sourced from the Census Population Estimates) within a state in the US, and the percentage of that population that experienced insufficient sleep (data sourced from the Behavioral Risk Factor Surveillance System). I also selected the average life expectancy for such populations (sourced from the National Center for Health Statistics) and the average number of poor mental health days they experienced (sourced from the Behavioral Risk Factor Surveillance System).
  
  The topic of mental health has always been of great interest to me, especially since I've personally had to deal with quite a few challenges myself and am well familiar with their impact in daily life, however, since I've been taking a sleep science class, and have always been curious as to sleep's relationship to mental help, I was hoping to explore data relating the two, and the general prevelance in the US. I expected to see a positive correlation between the percentage of people obtaining insufficient amounts of sleep and the average number of poor mental health days, as well as a negative correlation with the expected life expectancy because I feel that sleep plays a partially resorative role in a person's life, and chronic stress can lessen a body's ability to be resiliant. Overall I expected the northern states to have less sufficient sleep due to living in more industrial societies, so on average they would have poorer health.
  
  In the future, since this particular dataset has so many variables that may play important factors in a person's life, it would be interesting to see if more variables could be analyzed as they may be possibly confounding the variables and influencing the appeared correlations.

```{R}
library(readxl)
sleep_and_health_issues<-read_excel("C:\\Users\\sofia\\Desktop\\SDS 348\\Project 1\\sleep_and_health_issues.xlsx")
library(tidyverse)
library(dplyr)
library(datasets)
head(sleep_and_health_issues)
```

### Guidelines/Tidying

  My dataset was already tidy, but here I organised it a bit further by renaming the chosen variables to a more self-explanatory name.

```{R}  
data <- sleep_and_health_issues %>% select("Digit_FIPS_Code", "State_Abbreviation",
  "Poor_mental_health_days_raw_value", "Life_expectancy_raw_value", "Insufficient_sleep_raw_value", "Population_raw_value") %>% 
  rename(Digit_Code = Digit_FIPS_Code, PMHD = Poor_mental_health_days_raw_value, LE=Life_expectancy_raw_value, 
  IS=Insufficient_sleep_raw_value, POP=Population_raw_value, State_Abbreviation=State_Abbreviation)
glimpse(data)
```

2. Join your 2+ separate data sources into a single dataset

  I split the original data set into two: one containing the primary key, digit code, the state abbreviation of the state correlated to the city being measure, with the associated average number of poor mental health days and life expectancy, and the other with the remaining two unique variables (percentage of the population obtaining insufficient amounts of sleep, and the population of the city in question) in addition to the pimrary key (digit code). 
  
  I used full_join because it would result in having the same number of rows equal to union of IDs (digit code), which was a given as the primary key was shared in both dataset parts and each were a part of their original observation anyways, so all original data was retained and no rows would be dropped.
  
```{R}
part1<-data%>%select(Digit_Code, State_Abbreviation, PMHD, LE)
part2<-data%>%select(Digit_Code, IS, POP)
joinedData <- full_join(part1, part2, by = "Digit_Code")
glimpse(joinedData)
```

3. Create summary statistics
    
 Firstly I created a new variable named Sleepless_Wonders to describe the number of people obtaining insufficient amounts of sleep out of the population of people reported per city/observation. 
```{R}
organizzzed<-joinedData%>%group_by(State_Abbreviation)%>%select(3:6)%>%
  summarize_all(mean,na.rm=T)%>%arrange(PMHD)%>%
  mutate(Sleepless_Wonders=(IS * POP))
organizzzed
```
  Second, I filtered the data to find the statistical values relating to our home, Texas.
```{R}
texas_is_special<-organizzzed%>%filter(State_Abbreviation=="TX")
texas_is_special
```
  Continuing on I conducted a variety of summary statistics, calculating the min, max, variance, and standard deviation for the numeric variables. Summary was run at the top to obtain the min, max, median, mean, and the first and third quartile. However these values can also be elicited through the summarize_all function, where I called four of such functions at once. The values were called seperately for the two groups of columns so that all the values would fit on the page.
```{R}
summary(joinedData)
joinedData%>%group_by(State_Abbreviation)%>%select(3:4)%>%summarize_all(funs(min, max, var, sd),na.rm=T)
joinedData%>%group_by(State_Abbreviation)%>%select(5:6)%>%summarize_all(funs(min, max, var, sd),na.rm=T)
```
  Grouping by state, I was able to count the number of observations that fit for each, which revealed that Texas had a disproportionally large amount of data contributing to its means (155) in comparison to a state such as Delaware (4).
```{R}
joinedData%>%select(State_Abbreviation, Digit_Code)%>%group_by(State_Abbreviation)%>% 
  summarize(count=n())%>%arrange(desc(count))
```
  The third quartile for the numeric columns showed teh middle value between the median and the highest value of the data set where 75% of the data was contained below the reported value. So the majority of people experienced less than 5 days of poor mental health, with an average life expectancy of around 79 years. And about 36% of the average population (72235.5 people) experience insufficient sleep.
```{R}
joinedData%>%select(3:6)%>%summarize_if(is.numeric, list(Q3=quantile), probs=.75, na.rm=T)
```
  The mean number of days for a person from the states to experience poor mental health is about 3.9 days. The mean life expectancy is calculated to be about 77.5 years, and on average 33% of the mean population of 203713.7 people experience insufficient sleep.
```{R}
joinedData%>%select(3:6)%>%summarize_all(funs(mean), na.rm=T)
```
There were 3191 distinct values for number of poor mental health days, 3122 distinct values for life expectancy, 3191 distinct percentages of observation population values and 3135 distinct population sizes in my dataset.
```{R}
joinedData%>%select(3:6)%>%summarize_all(funs(n_distinct), na.rm=T)
```
The median for number of poor mental health days is 3.94 days. The median life expectancy is 77.57 years, median population being 26476 people, and the median of percents of the populations obtaining insufficient sleep being about 32.96%.
```{R}
joinedData%>%select(3:6)%>%summarize_all(funs(median), na.rm=T)
```
  The inter-quartile range for each numeric column described teh statistical dispersion, or middle difference of value between the 75th and 25th quartiles. The fact that the poor mental health days, life expectancy, and insufficient sleep variables had relatively low values shows you that a fairly large portion of the observations had similar values, which could possibly mean they're controlled by a common environmental factor.
```{R}
joinedData%>%select(3:6)%>%summarize_all(funs(IQR), na.rm=T)
```
  The median absolute deviation value for each numeric column shows the variability of a univariate sample of quantitative data.The low values are consistent with my previous hypothesis statement.
```{R}
joinedData%>%select(3:6)%>%summarize_all(funs(mad), na.rm=T)
```
 By pivoting longer I was able to globalize the data observation points to find the mean for each of the numeric variables across all states and observations. I removed all NA values after ungrouping by the state abbreviation and regrouping by the variables. Finally I summarized the mean of each of the values.
```{R}
joinedData_pivoting_longer<- joinedData%>% pivot_longer(3:6,names_to="Variables", values_to="Values")%>%ungroup(State_Abbreviation)%>%group_by(Variables)%>%na.omit%>%summarise(mean(Values))
joinedData_pivoting_longer
```
 I then pivoted wider to help format and put the variables lined up in the columns.
```{R}
joinedData_pivoting_wider<-joinedData_pivoting_longer%>%pivot_wider(names_from = "Variables", values_from = "mean(Values)")
joinedData_pivoting_wider
```
The correlation matrix between the number of poor mental health days an individual has and the percentage of days that they have insufficient sleep ended up having a reasonably strong positive correlation, meaning that with an increase in the percentage of people obtaining insufficient sleep, there was a rise in the average number of poor mental health days expereienced.
```{R}
joinedData%>%na.omit%>%summarize(cor(PMHD, IS))
```
 
4. Make visualizations (three plots)
    
  The correlation heatmap between the numeric variables reveals that, excludind correlations between same variables, the two variables that shared the strongest correlation were the number of poor mental health days, and the percentage of people getting insufficient sleep, and was postive, The weakest correlation was a negative one between the population size and the number of poor mental health days. Though there was a fairly strong negative correlation between life expectancy and poor mental health days, which is understandable, and yet another similarly strong negative correlation between life expectancy and insufficient sleep.
```{R}
#Correlation heatmap of numeric variables.
CM<-joinedData%>%na.omit%>%select_if(is.numeric)%>%select(-Digit_Code)
cor(CM)

tidycor<-cor(CM)%>%as.data.frame%>%
rownames_to_column%>%
pivot_longer(-1,names_to="name",values_to="correlation")
tidycor

tidycor%>%ggplot(aes(rowname,name,fill=correlation))+
geom_tile()+
scale_fill_gradient2(low="purple",mid="white",high="pink")+  
geom_text(aes(label=round(correlation,2)),color = "black", size = 5)+ 
theme(axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5))+ 
coord_fixed()+ 
ggtitle("Correlation Heatmap Between \n Numeric Variables") + 
theme(plot.title = element_text(hjust = 0.5)) + 
ylab("Variables") + xlab("Variables")
```
The first plot was split into 3 bar charts because my categorical variable has 50 categories, so I figured it was easier to visualize when separated a bit out. I explored the relationship between life expectancy and population within each state. There appears to be no correlation at all because states who have some of the largest populations have similar life expectancies as those with smaller ones, and they are spread over the entire restulting range. The reason I decided to compare these variables was because I hypothesized that states with a larger population would most likely have a more establish healthcare infrastructure which would lead to an increased life expectancy.
```{R}
#Plot 1
statesAK<-joinedData%>%slice(1:1130)%>%select(State_Abbreviation, LE, POP)%>%group_by(State_Abbreviation)%>%na.omit
statesAK2<-statesAK%>%summarize(LE_MEan = mean(LE, na.rm=T), POP_Sum = sum(POP, na.rm=T))
statesLN<-joinedData%>%slice(1131:1922)%>%select(State_Abbreviation, LE, POP)%>%group_by(State_Abbreviation)%>%na.omit
statesLN2<-statesLN%>%summarize(LE_MEan = mean(LE, na.rm=T), POP_Sum = sum(POP, na.rm=T))
statesOW<-joinedData%>%slice(1923:3192)%>%select(State_Abbreviation, LE, POP)%>%group_by(State_Abbreviation)%>%na.omit
statesOW2<-statesOW%>%summarize(LE_MEan = mean(LE, na.rm=T), POP_Sum = sum(POP, na.rm=T))

ggplot(statesAK2, aes(x=State_Abbreviation, y=LE_MEan)) +
   theme(axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5)) + 
  geom_bar(aes(fill=POP_Sum),stat = "summary")+
   ggtitle("Life Expectancy vs State by Populations") + 
  ylab("Mean Life Expectancy (years)") + xlab("State Abbreviation") + 
  theme(plot.title = element_text(hjust = 0.5))+ 
  scale_fill_gradient(low = "blue", high = "red", na.value = NA)

ggplot(statesLN2, aes(x=State_Abbreviation, y=LE_MEan)) +
   theme(axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5)) + 
  geom_bar(aes(fill=POP_Sum),stat = "summary")+ 
  ggtitle("Life Expectancy vs State by Populations") + 
  ylab("Mean Life Expectancy (years)") + xlab("State Abbreviation") + 
  theme(plot.title = element_text(hjust = 0.5))+ 
  scale_fill_gradient(low = "blue", high = "red", na.value = NA)

ggplot(statesOW2, aes(x=State_Abbreviation, y=LE_MEan)) +
   theme(axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5)) + 
  geom_bar(aes(fill=POP_Sum),stat = "summary")+ 
  ggtitle("Life Expectancy vs State by Populations") + 
  ylab("Mean Life Expectancy (years)") + xlab("State Abbreviation") + 
  theme(plot.title = element_text(hjust = 0.5))+ 
  scale_fill_gradient(low = "blue", high = "red", na.value = NA)
```
The next plot I also split into multiple parts due to having too many categories. I compared the percentage of people obtaining insufficient amounts of sleep with the amount of poor mental health days per state. Overall there was an overwhelmingly obvious positive correlation amongst all the states showing that those who had less sleep (increase in insufficient sleep) had an increase in poor mental health days experienced. Since the states were color coded, you can see how the observations tended to cluster around certain values per state, which would make it slightly harder to visualize the correlation individually, however we can see that certain states have overall lower levels of both, like South Dakota, versus having overal higher levels for both like West Virigina or Kentucky. As a thought experience, I also added another layer of variables and included the population size per observation in the second graph, represented by the size of the points to see if there were any correlations between which states would have these lower correlations between sleep and mental health. But again none was found.
```{R}
#Plot 2
library(ggplot2)
library(dplyr)
statesAG <-joinedData%>%slice(1:556)%>%
  mutate(Insufficient_Sleepers=(IS*POP))%>%
  select(State_Abbreviation, IS, PMHD, Insufficient_Sleepers)
statesHMD<-joinedData%>%slice(557:1237)%>%
  mutate(Insufficient_Sleepers=(IS*POP))%>%
  select(State_Abbreviation, IS, PMHD, Insufficient_Sleepers, POP)
statesMNJ<-joinedData%>%slice(1238:1825)%>%
  mutate(Insufficient_Sleepers=(IS*POP))%>%
  select(State_Abbreviation, IS, PMHD, Insufficient_Sleepers)
statesNSC<-joinedData%>%slice(1826:2402)%>%
  mutate(Insufficient_Sleepers=(IS*POP))%>%
  select(State_Abbreviation, IS, PMHD, Insufficient_Sleepers)
statesSDW<-joinedData%>%slice(2403:3192)%>%
  mutate(Insufficient_Sleepers=(IS*POP))%>%
  select(State_Abbreviation, IS, PMHD, Insufficient_Sleepers)

ggplot(statesAG, aes(PMHD,IS))+
geom_point(mapping=aes(color = State_Abbreviation),)+
  ggtitle("Insufficient Sleep Per State Correlated to \n Number of Poor Mental Health Days") + 
  ylab("Percent of Population Having Insufficient Sleep") + 
  scale_x_continuous("Poor Mental Health Days (count)", breaks = c(2.5, 3.5, 4.5, 5.5)) + 
  theme(plot.title = element_text(hjust = 0.5))+
  scale_color_brewer(palette="Set3")

ggplot(statesHMD, aes(PMHD,IS, size= POP))+
geom_point(mapping=aes(color = State_Abbreviation),)+ 
    scale_size(range = c(.1, 12), name="Population")+ 
  ggtitle("Insufficient Sleep Per State Correlated to \n Number of Poor Mental Health Days") + 
  ylab("Percent of Population Having Insufficient Sleep") + 
  scale_x_continuous("Poor Mental Health Days (count)", breaks = c(3, 4, 5)) + 
  theme(plot.title = element_text(hjust = 0.5))+
  scale_color_brewer(palette="Set3")

ggplot(statesMNJ, aes(PMHD,IS))+
geom_point(mapping=aes(color = State_Abbreviation),)+ 
  ggtitle("Insufficient Sleep Per State Correlated to \n Number of Poor Mental Health Days") + 
  ylab("Percent of Population Having Insufficient Sleep") + 
  scale_x_continuous("Poor Mental Health Days (count)", breaks = c(3, 4, 5)) +
  theme(plot.title = element_text(hjust = 0.5))+
  scale_color_brewer(palette="Set3")

ggplot(statesNSC, aes(PMHD,IS))+
geom_point(mapping=aes(color = State_Abbreviation),)+ 
  ggtitle("Insufficient Sleep Per State Correlated to \n Number of Poor Mental Health Days") + 
  ylab("Percent of Population Having Insufficient Sleep") + 
  scale_x_continuous("Poor Mental Health Days (count)", breaks = c(2.5, 3.5, 4.5, 5.5)) +
  theme(plot.title = element_text(hjust = 0.5))+
  scale_color_brewer(palette="Set3")

ggplot(statesSDW, aes(PMHD,IS))+
geom_point(mapping=aes(color = State_Abbreviation),)+ 
  ggtitle("Insufficient Sleep Per State Correlated to \n Number of Poor Mental Health Days") + 
  ylab("Percent of Population Having Insufficient Sleep") + 
  scale_x_continuous("Poor Mental Health Days (count)", breaks = c(2.5, 3.5, 4.5, 5.5)) +
  theme(plot.title = element_text(hjust = 0.5))+
  scale_color_brewer(palette="Set3")
```

5. Perform k-means/PAM clustering or PCA on (at least) your numeric variables.
    
We want to determine how mnay clusters to pick. To do so we want to first create a new vector array to hold the data results, which we iterate from 2 to 10, placing the value in "i" so that the i position of the vector array is set to the selected data as its ran through pam(k=i, diss=T). Essentially we are computing the WSS for the range of cluster counts by using the for-loop. The daisy function creates the dissimilarity matrix, which is determined by the number of clusters at each point, and since it is a distanct function in the cluster package, we are able to calculate the gower dissimilarities, or the "distance" between two units. Once we have the distanct measure, we want to compare and see how the observations group together in space defined by our variables, so we plot the within-cluster SS (WSS or silwidth) against the number of clusters k.
The plot below reveals that the highest point is at x=2, which means that we should pick two clusters with PAM because at that point the clusters have the best ratio of having distance between clusters medoids and the smallest within-cluster distance. The reason we calculate the silhouette width to calculate the number of clusters we want to compare is because it indexes how well the points are assigned to the cluster so that the higher width means the more cohesive the cluster is, which is what is desired.
```{R}
library(cluster)
library(GGally)

silwidth<-vector()
for(i in 2:10){
silwidth[i]<-(joinedData%>%select(3:6)%>%daisy("gower")%>%pam(k=i,diss=T))$silinfo$avg.width
}
ggplot()+geom_path(aes(x=2:10,y=silwidth[2:10]))+ 
   theme(plot.title = element_text(hjust = 0.5))+ 
  ggtitle("PAM k clusters vs Silhouette width")+ 
  ylab("Silhouette Width") +
  xlab("k clusters")
```
We then visualize all the pairwise combinations between our four variables. Using the two clusters in PAM we are able to analyze the correlations between each pairwise combination and compairison in numeric and graph form. The strongest correlation is positive and is between insufficient sleep and poor mental health days. The weakest is negative and is between population and insufficient sleep.The two colors present correlate to each of the two clusters' data. Without the color its hard to differentiate the two clusters due to a large amount of overlap.
```{R}
fdataclust<-joinedData%>%select(3:6)%>%pam(k=2)
joinedData%>%ggpairs(columns = 3:6)

joinedData%>%mutate(cluster=as.factor(fdataclust$clustering))%>%
ggpairs(columns = 3:6,aes(color=cluster))
```
The first line describes the medoids, or the center value of each of the cluster in relation to each of the four numeric variables. Then to find the final medoids we slide the data to see which states were most representative of the clusters which turned out to be Tennessee for cluster 1 and Virginia for cluster 2. The average width was 0.9734386 which means that a strong structure has been found overall, and individuall, there was no substantial structrue found for cluster one with an average silhouette width of 0.1905604 and a strong structure for cluster two with a value of 0.9816194.
```{R}
fdataclust$medoids
joinedData%>%slice(fdataclust$id.med)
fdataclust$silinfo$avg.width
fdataclust$silinfo$clus.avg.widths
```

<P style="page-break-before: always">
...
```{R eval=F}
data(package = .packages(all.available = TRUE))
```
...